data:
  overrides: ["+data=data_exp"]
  version_base: None 
  config_path: "../config/banknifty/"
model:
  overrides: ["+data=data_exp","+model=pycaret"]
  version_base: None 
  config_path: "../config/banknifty/"