paths:
  model_prefix: pycaret
  model_spec_name: modelling.model_specs.model_pycaret_v4
  model_files: /content/drive/MyDrive/Work/trading/model/
  model_base_loc: ${model.paths.model_files}${data.paths.ticker_name}/${data.paths.data_create_date}/
  model_name: ${model.paths.model_prefix}_${data.paths.ticker_name}_${model.data.target_column}_${model.trainer.create_model.estimator}
  model_save_path: ${model.paths.model_base_loc}${model.paths.model_name}
  model_type_save_path: ${model.paths.model_base_loc}${model.paths.model_name}
  model_parameter_save_path: ${model.paths.model_type_save_path}_hyperparameter.pkl
  model_evaluation_save_path: ${model.paths.model_type_save_path}_evaluation.pkl
  model_prediction_save_path: ${model.paths.model_type_save_path}_prediction.pkl
  model_metadata_save_path: ${model.paths.model_type_save_path}_metadata.pkl

  model_setup_save_path: ${model.paths.model_base_loc}${model.paths.model_name}_setup.pkl
  model_comparison_save_path: ${model.paths.model_base_loc}${model.paths.model_name}_comparison.pkl
  model_creation_save_path: ${model.paths.model_base_loc}${model.paths.model_name}_creation.pkl
  model_tuned_save_path: ${model.paths.model_base_loc}${model.paths.model_name}_tuned.pkl

  previous_load_setup: False
  previous_load_comparison: False
  previous_load_creation: False
  previous_load_tuned: False
  print_option: print
  
data:
  splits:
    load_train: True
    load_valid: True
    load_test: False
  splits_type: normal
  splits_details:
    train_date_range_ll: '2014-01-01'
    train_date_range_ul: '2021-10-31'
    valid_date_range_ll: '2021-11-01'
    valid_date_range_ul: '2022-05-31'
    test_date_range_ll: '2022-06-01'
    test_date_range_ul: '2022-08-30'
  sampling_type: frac
  sampling_frac: 0.6
  target_column: label_-15_1min_close_SL
  label_columns: [label_-30_1min_close,label_-60_1min_close,'label_-15_1min_close','label_-45_1min_close',label_-30_1min_close_SL,label_-60_1min_close_SL,'label_-15_1min_close_SL','label_-45_1min_close_SL']
  drop_columns: ['Unnamed: 0',HILOl_13_21,HILOs_13_21,MCGD_10,PSARl_0.02_0.2,PSARs_0.02_0.2,QQEl_14_5_4.236,QQEs_14_5_4.236,SUPERTl_7_3.0,SUPERTs_7_3.0,PVDR_close_w,PVDR_close_w_MAX_MIN,PVDR_open_w,PVDR_open_w_MAX_MIN,PVDR_high_w,PVDR_high_w_MAX_MIN,PVDR_low_w,PVDR_low_w_MAX_MIN,'CUC_MCGD_10','PerChg_MCGD_10_15_None','PerChg_MCGD_10_30_None','PerChg_MCGD_10_45_None','PerChg_MCGD_10_60_None','CUC_PSARs_0.02_0.2','QQEs_14_5_4.236','CUC_SUPERTl_7_3.0','CUC_SUPERTs_7_3.0','CUC_PSARl_0.02_0.2','CUC_HILOl_13_21','CUC_HILOs_13_21']
  id_col: None

evaluation:
  eval_metric: accuracy
  load_predictor_from_path: 0

prediction:
  load_predictor_from_path: 0

trainer:
  generic: 
    model_time_limit: 12000
    use_default_parameter: 0
    optimize: 0
    load_parameter_from_path: False
    trainer_option: 2
    presets: good_quality
  setup:
    target: ${model.data.target_column}
    train_size: 0.7
    preprocess: True
    imputation_type: iterative
    iterative_imputation_iters: 2
    categorical_features: null
    categorical_imputation: constant
    categorical_iterative_imputer: lightgbm
    ordinal_features: null
    high_cardinality_features: null
    high_cardinality_method: frequency
    numeric_features: null
    numeric_imputation: mean
    numeric_iterative_imputer: lightgbm
    date_features: null
    ignore_features: null
    normalize: False
    normalize_method: zscore
    transformation: False
    transformation_method: yeo-johnson
    handle_unknown_categorical: False
    unknown_categorical_method: least_frequent
    pca: False
    pca_method: kernel
    pca_components: null
    ignore_low_variance: False
    combine_rare_levels: True
    rare_level_threshold: 0.1
    bin_numeric_features: null
    remove_outliers: False
    outliers_threshold: 0.05
    remove_multicollinearity: True
    multicollinearity_threshold: 0.9
    remove_perfect_collinearity: True
    create_clusters: False
    cluster_iter: 20
    polynomial_features: False
    polynomial_degree: 2
    trigonometry_features: False
    polynomial_threshold: 0.1
    group_features: null
    group_names: null
    feature_selection: True
    feature_selection_threshold: 0.8
    feature_selection_method: classic
    feature_interaction: False
    feature_ratio: False
    interaction_threshold: 0.01
    fix_imbalance: False
    fix_imbalance_method: null
    data_split_shuffle: True
    data_split_stratify: True
    fold_strategy: stratifiedkfold
    fold: 10
    fold_shuffle: False
    fold_groups: null
    n_jobs: -1
    use_gpu: False
    custom_pipeline: null
    html: True
    session_id: 1234
    log_experiment: False
    experiment_name: Lighgbm_16min
    experiment_custom_tags: null
    log_plots: False
    log_profile: False
    log_data: False
    silent: False
    verbose: True
    profile: False

  compare_models:
    include: ['xgboost', 'lightgbm','catboost','et','dummy','rf', 'knn','ada']
    fold: 3
    n_select: 6
    sort: 'f1'

  create_model:
    estimator: lightgbm
    fold: 4
    return_train_score: True

  tune_model:
    return_tuner: False
    search_library: optuna
    early_stopping: Hyperband
    optimize: F1
    fold: 5
  check_metric:
    metric: F1 
  stack_model:
    round: 4
    method: auto
    restack: True
  blend_model:
    fold: 4
    method: soft
    choose_better: True 